import type {
  DocsConfig,
  GenerateDocsOptions,
  LlmsMeta,
  ScanContext,
  ScanResult,
} from "./types.ts";
import { mkdirSync, writeFileSync } from "node:fs";
import { LAYOUT_SFC } from "./sfc.ts";
import { buildLlms } from "./llms.ts";
import { buildSidebar } from "./sidebar.ts";
import { defined } from "@vow/core";
import { manifestModule } from "./manifest.ts";
import { materialiseAll } from "./materialise.ts";
import path from "node:path";
import { scanAll } from "./scan.ts";

const BANNER = "<!-- Generated by @vow/docs — do not edit. -->\n";

/** The resolved config + scan output a write step reads — bundled so each helper stays under 3 params. */
interface BuildOutput {
  readonly config: DocsConfig;
  readonly result: ScanResult;
  readonly groups: readonly string[] | undefined;
}

/** The llms.txt site metadata — the description key is present only when one was configured. */
function llmsMeta(config: Readonly<DocsConfig>, description: string | undefined): LlmsMeta {
  if (defined(description)) {
    return { description, title: config.title };
  }
  return { title: config.title };
}

/** Write the llms.txt pair into the served `public/` dir, when a `publicDir` was configured. */
function writeLlmsIfRequested(
  build: Readonly<BuildOutput>,
  // oxlint-disable-next-line typescript/prefer-readonly-parameter-types -- `opts` carries Shiki's `Highlighter`, a platform type.
  opts: Readonly<GenerateDocsOptions>,
): readonly string[] {
  if (!defined(opts.publicDir)) {
    return [];
  }
  mkdirSync(opts.publicDir, { recursive: true });
  const meta = llmsMeta(build.config, opts.description);
  const llms = buildLlms(build.result.llmsEntries, meta, build.groups);
  const indexPath = path.join(opts.publicDir, "llms.txt");
  const fullPath = path.join(opts.publicDir, "llms-full.txt");
  writeFileSync(indexPath, llms.index, "utf8");
  writeFileSync(fullPath, llms.full, "utf8");
  return [indexPath, fullPath];
}

/** Write the routes manifest + the layout SFC, returning their paths. */
function writeChrome(outDir: string, build: Readonly<BuildOutput>): readonly string[] {
  const { config, groups, result } = build;
  const manifest = path.join(outDir, "vow-docs.routes.ts");
  const sidebar = buildSidebar(result.pages, groups);
  const module = manifestModule({
    config,
    pages: result.pages,
    search: result.search,
    sidebar,
    tocByPath: result.tocByPath,
  });
  writeFileSync(manifest, module, "utf8");
  const layout = path.join(outDir, "vow-docs.layout.vue");
  writeFileSync(layout, `${BANNER}${LAYOUT_SFC}`, "utf8");
  return [manifest, layout];
}

/**
 * Scan a content folder → a generated prose `.vue` per `.md` plus a manifest (routes + sidebar). The
 * sidebar is built from each page's `group`/`order`/`title` frontmatter. Returns the written paths.
 */
export function generateDocs(
  contentDir: string,
  outDir: string,
  // oxlint-disable-next-line typescript/prefer-readonly-parameter-types -- `opts` carries Shiki's `Highlighter`, a platform type.
  opts: Readonly<GenerateDocsOptions> = {},
): string[] {
  mkdirSync(outDir, { recursive: true });
  const context: ScanContext = {
    base: opts.base,
    contentDir,
    highlighter: opts.highlighter,
    outDir,
  };
  const result = scanAll(context);
  const config: DocsConfig = {
    base: opts.base ?? "",
    nav: opts.nav ?? [],
    title: opts.title ?? "Docs",
  };
  const build: BuildOutput = { config, groups: opts.groups, result };
  return [
    ...result.written,
    ...writeChrome(outDir, build),
    ...writeLlmsIfRequested(build, opts),
    ...materialiseAll(outDir, result.used, contentDir),
  ];
}
