import type { LlmsEntry, LlmsFiles, LlmsMeta } from "./types.ts";
import { defined } from "@vow/core";
import { sectionOrder } from "./sidebar.ts";

/** Trim a paragraph to its first real sentence (everything up to the first ". " boundary). */
function toFirstSentence(text: string): string {
  const dot = text.indexOf(". ");
  if (dot === -1) {
    return text.trim();
  }
  return text.slice(0, dot + 1).trim();
}

/** The first real sentence of a markdown body — a one-line description for the llms.txt index. */
export function firstSentence(body: string): string {
  const para = body
    .split("\n\n")
    .map((paragraph) => paragraph.trim())
    .find((paragraph) => paragraph !== "" && !/^[#:`>|-]/u.test(paragraph));
  if (!defined(para)) {
    return "";
  }
  const text = para
    .replaceAll(/\[([^\]]+)\]\([^)]+\)/gu, "$1")
    .replaceAll(/[*_`]/gu, "")
    .replaceAll("\n", " ");
  return toFirstSentence(text);
}

/** Strip doc-only blocks (the whole live `::: demo … :::` placeholder) — no text for an LLM reader. */
export const cleanBody = (body: string): string =>
  body
    .replaceAll(/^::: ?(?:demo|timeline)\b[\s\S]*?\n:::[ \t]*$/gmu, "")
    // An inline badge -> its label
    .replaceAll(/:badge\[([^\]]+)\](?:\{[^}]*\})?/gu, "$1")
    // An inline icon -> dropped (it's decorative)
    .replaceAll(/:icon\[[^\]]+\]\s?/gu, "")
    .replaceAll(/\n{3,}/gu, "\n\n")
    .trim();

/** Group the llms entries by their `group` (ungrouped entries are dropped). */
function groupEntries(entries: readonly LlmsEntry[]): Map<string, LlmsEntry[]> {
  const byGroup = new Map<string, LlmsEntry[]>();
  for (const entry of entries) {
    if (defined(entry.group)) {
      byGroup.set(entry.group, [...(byGroup.get(entry.group) ?? []), entry]);
    }
  }
  return byGroup;
}

/** By order, then by path — so a parent page (a path prefix, e.g. /primitives) precedes its children. */
function inOrder(entries: readonly LlmsEntry[]): LlmsEntry[] {
  return entries.toSorted(
    (first, second) => first.order - second.order || first.path.localeCompare(second.path),
  );
}

/** One entry's index line: `- [Title](/path): first sentence` (the description is optional). */
function indexLine(entry: Readonly<LlmsEntry>): string {
  const desc = firstSentence(entry.body);
  if (desc === "") {
    return `- [${entry.title}](${entry.path})`;
  }
  return `- [${entry.title}](${entry.path}): ${desc}`;
}

/** The header lines shared by both files — the title, then an optional one-line description. */
function header(title: string, meta: Readonly<LlmsMeta>): string[] {
  const lines = [title, ""];
  if (defined(meta.description)) {
    lines.push(`> ${meta.description}`, "");
  }
  return lines;
}

/** One group's lines for both files — the index links and the full inlined bodies. */
function sectionLines(
  group: string,
  pages: readonly LlmsEntry[],
): {
  readonly index: readonly string[];
  readonly full: readonly string[];
} {
  const index = [`## ${group}`];
  const full: string[] = [];
  for (const page of inOrder(pages)) {
    index.push(indexLine(page));
    full.push("---", "", `> Source: ${page.path}`, "", cleanBody(page.body), "");
  }
  index.push("");
  return { full, index };
}

/**
 * Build the `llms.txt` pair from the scanned pages — the [llmstxt.org](https://llmstxt.org) convention:
 * `index` is a curated map (title + grouped links + one-line descriptions); `full` inlines every page's
 * markdown, so an LLM loads the whole documentation in one request. vow-native — generated by our own
 * docs pipeline, the same content the site renders, dumped for an LLM to load in one request.
 */
export function buildLlms(
  entries: readonly LlmsEntry[],
  meta: Readonly<LlmsMeta>,
  groups: readonly string[] = [],
): LlmsFiles {
  const byGroup = groupEntries(entries);
  const index = header(`# ${meta.title}`, meta);
  const full = header(`# ${meta.title} — full documentation`, meta);
  for (const group of sectionOrder([...byGroup.keys()], groups)) {
    const pages = byGroup.get(group);
    if (defined(pages)) {
      const section = sectionLines(group, pages);
      index.push(...section.index);
      full.push(...section.full);
    }
  }
  return { full: `${full.join("\n").trimEnd()}\n`, index: `${index.join("\n").trimEnd()}\n` };
}
