import { DEMOS, PRIMITIVES, PROSE_COMPONENTS } from "./sfc.ts";
import { gitRemoteUrl, gitTimeline } from "@vow/observability";
import type { Demo } from "./types.ts";
import { defined } from "@vow/core";
import { emitTimelineSfc } from "@vow/emit-view";
import path from "node:path";
import { writeFileSync } from "node:fs";

const BANNER = "<!-- Generated by @vow/docs — do not edit. -->\n";
const TIMELINE_DEPS = ["Badge", "Collapsible"] as const;

/** A `<Name>.vue` writer — `name` and the SFC source; already-written names are no-ops. */
export type ComponentWriter = (name: string, sfc: string) => void;

/** A writer that materialises each `<Name>.vue` once, plus a reader for the paths it wrote. */
interface Materialiser {
  readonly write: ComponentWriter;
  readonly written: () => readonly string[];
}

/** SFC source with the generated banner prepended (unless the source already carries an HTML comment). */
function withBanner(sfc: string): string {
  if (sfc.startsWith("<!--")) {
    return sfc;
  }
  return BANNER + sfc;
}

/** A `<Name>.vue` writer that materialises each component once, holding its own dedup + path state. */
function makeMaterialiser(outDir: string): Materialiser {
  const done = new Set<string>();
  const paths: string[] = [];
  return {
    write: (name, sfc) => {
      if (!done.has(name)) {
        done.add(name);
        const file = path.join(outDir, `${name}.vue`);
        writeFileSync(file, withBanner(sfc), "utf8");
        paths.push(file);
      }
    },
    written: () => paths,
  };
}

/** Materialise a demo: its adapter, every composed part, then the live wrapper SFC. */
function writeDemo(write: ComponentWriter, name: string, demo: Readonly<Demo>): void {
  write(demo.adapter, demo.emit());
  for (const part of demo.also ?? []) {
    write(part.name, part.emit());
  }
  write(name, demo.sfc);
}

/** Materialise the timeline component plus the primitives it composes (type chips + per-date collapse). */
function writeTimeline(write: ComponentWriter, name: string, contentDir: string): void {
  for (const dep of TIMELINE_DEPS) {
    const adapter = PRIMITIVES[dep];
    if (defined(adapter)) {
      write(dep, adapter());
    }
  }
  write(name, emitTimelineSfc(gitTimeline(contentDir), gitRemoteUrl(contentDir)));
}

/** Materialise a bare reference — a prose component (a fixed SFC) or a primitive adapter (emitted). */
function writeBare(write: ComponentWriter, name: string): void {
  const prose = PROSE_COMPONENTS[name];
  if (defined(prose)) {
    write(name, prose);
  }
  const primitive = PRIMITIVES[name];
  if (defined(primitive)) {
    write(name, primitive());
  }
}

/** Materialise one referenced component — prose component, bare primitive, timeline, or demo. */
function materialise(write: ComponentWriter, name: string, contentDir: string): void {
  writeBare(write, name);
  if (name === "VowTimeline") {
    writeTimeline(write, name, contentDir);
  }
  const demo = DEMOS[name];
  if (defined(demo)) {
    writeDemo(write, name, demo);
  }
}

/** A referenced name has nothing to materialise — neither a built-in nor a known demo/primitive. */
function isUnknown(name: string): boolean {
  return (
    name !== "Icon" &&
    name !== "VowTimeline" &&
    !defined(PROSE_COMPONENTS[name]) &&
    !defined(DEMOS[name]) &&
    !defined(PRIMITIVES[name])
  );
}

/** Fail loud when a page references a component with nothing to generate (e.g. an unknown `::: demo`). */
function assertAllKnown(used: readonly string[]): void {
  const unknown = used.filter((name) => isUnknown(name));
  if (unknown.length > 0) {
    const demos = Object.keys(DEMOS)
      .map((name) => name.replace(/^VowDemo/u, "").toLowerCase())
      .join(", ");
    throw new Error(
      `docs: no component to generate for ${unknown.join(", ")}. ` +
        `For "::: demo <primitive>", the known primitives are: ${demos}.`,
    );
  }
}

/**
 * Materialise every referenced component into `outDir/<Name>.vue` and assert each one is known — the
 * prose SFCs import `./<Name>.vue`, so an unknown reference must fail loud, not emit a dangling import.
 * Returns the written `<Name>.vue` paths.
 */
export function materialiseAll(
  outDir: string,
  used: readonly string[],
  contentDir: string,
): readonly string[] {
  const materialiser = makeMaterialiser(outDir);
  for (const name of used) {
    materialise(materialiser.write, name, contentDir);
  }
  assertAllKnown(used);
  return materialiser.written();
}
