import type { Vow } from "@vow/core";

/**
 * vow's view emitter — `emit view` made real.
 *
 * A view renders a list of an entity's rows. Text fields render as-is; boolean fields render as the
 * emitted, accessible <Checkbox> (generated by @vow/emit-primitive over @vow/headless), making the
 * row interactive. The view holds local state and ships minimal structural styles so the list is
 * readable out of the box; the design system layers on top. Real persistence comes via an adapter.
 */

const escapeHtml = (s: string): string =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

/** kebab-case slug → PascalCase type name (`task` → `Task`). */
const pascalCase = (slug: string): string =>
  slug
    .split("-")
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("");

/** A Vue view over an entity: a typed `items` prop into local state, one row per item. */
export function emitViewSfc(view: Vow, entity: Vow): string {
  if (view.fulfills?.kind !== "emit" || view.fulfills.as !== "view") {
    throw new Error(`emit-view: vow "${view.slug}" is not an \`emit view\``);
  }
  if (entity.fulfills?.kind !== "emit" || entity.fulfills.as !== "entity") {
    throw new Error(`emit-view: view "${view.slug}" must be \`of\` an \`emit entity\``);
  }
  const type = pascalCase(entity.slug);
  const root = `vow-view-${view.slug}`;
  const hasBoolean = entity.fields.some((f) => f.type === "boolean");
  const cells = entity.fields.map((f) =>
    f.type === "boolean"
      ? `        <Checkbox v-model="item.${f.name}" label="${f.name}" />`
      : `        <span class="field-${f.name}">{{ item.${f.name} }}</span>`,
  );
  const head = [
    `<script setup lang="ts">`,
    `// Generated from vow "${view.slug}" (a view of "${entity.slug}"). The vow tree is the source — do not edit.`,
    `import { ref } from "vue";`,
    `import type { ${type} } from "./${entity.slug}.ts";`,
  ];
  if (hasBoolean) head.push(`import Checkbox from "./Checkbox.vue";`);
  head.push(
    ``,
    `const props = defineProps<{ items: ${type}[] }>();`,
    `const rows = ref<${type}[]>(props.items.map((item) => ({ ...item })));`,
    `</script>`,
  );
  return [
    ...head,
    ``,
    `<template>`,
    `  <section class="${root}">`,
    `    <h1>${escapeHtml(view.intent)}</h1>`,
    `    <ul>`,
    `      <li v-for="(item, i) in rows" :key="i">`,
    ...cells,
    `      </li>`,
    `    </ul>`,
    `  </section>`,
    `</template>`,
    ``,
    `<style scoped>`,
    `.${root} {`,
    `  font-family: system-ui, sans-serif;`,
    `  max-width: 32rem;`,
    `  margin: 2rem auto;`,
    `}`,
    `.${root} h1 {`,
    `  font-size: 1.4rem;`,
    `  margin-bottom: 1rem;`,
    `}`,
    `.${root} ul {`,
    `  list-style: none;`,
    `  padding: 0;`,
    `  display: flex;`,
    `  flex-direction: column;`,
    `  gap: 0.5rem;`,
    `}`,
    `.${root} li {`,
    `  display: flex;`,
    `  align-items: center;`,
    `  justify-content: space-between;`,
    `  gap: 1rem;`,
    `  padding: 0.6rem 0.85rem;`,
    `  border: 1px solid #e3e3e3;`,
    `  border-radius: 0.5rem;`,
    `}`,
    `</style>`,
    ``,
  ].join("\n");
}
